# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Flurl
tagline:          Fluent URL Builder and Testable HTTP for .NET
description:      Fluent URL Builder and Testable HTTP for .NET
url:              http://tmenier.github.io/Flurl

author:
  name:           Todd Menier
  url:            https://twitter.com/tmenier

paginate:         1

github:
  repo:           https://github.com/tmenier/flurl
